//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	001	USD	US Dollar	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///2	002	AMD	Armenian Dram	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///3	003	AUD	Australian Dollar	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///4	004	THB	Thai Baht	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///5	005	CAD	Canadian Dollar	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///6	006	DKK	Danish Krone	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000
        ///7	007	EUR	EURO	1	2009-07-11 14:43:19.000	2009-07-11 14:43:19.000        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DimCurrency {
            get {
                return ResourceManager.GetString("DimCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	680	11000		Jon	V	Yang	0	1966-04-08	M		M	jon24@adventure-works.com	90000.0000	2	0	Bachelors	Professional	1	0	3761 N. 14th St		1 (11) 500 555-0162	2001-07-22	Person		1	2009-10-01 00:00:00.000	2009-10-01 00:00:00.000
        ///2	692	11001		Eugene	L	Huang	0	1965-05-14	S		M	eugene10@adventure-works.com	60000.0000	3	3	Bachelors	Professional	0	1	2243 W St.		1 (11) 500 555-0110	2001-07-18	Person		1	2009-10-01 00:00:00.000	2009-10-01 00:00:00.000
        ///3	493	11002		Ruben		Torres	0	1965-08-12	M		M	ruben35@adventure-works.com	600 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DimCustomer {
            get {
                return ResourceManager.GetString("DimCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2005-01-01 00:00:00.000	2005-01-01	2005/01/01	2005	Year 2005	20051	H1	20051	Q1	200501	January	200501	Week 1	2005017	Saturday	2005	FiscalYear 2005	20051	H1	20051	Q1	200501	Month 1	WeekEnd	0	None	Holiday	Spring/Back to Business	Holiday
        ///2005-01-02 00:00:00.000	2005-01-02	2005/01/02	2005	Year 2005	20051	H1	20051	Q1	200501	January	200502	Week 2	2005021	Sunday	2005	FiscalYear 2005	20051	H1	20051	Q1	200501	Month 1	WeekEnd	0	None	Holiday	Spring/Back to Business	Holiday
        ///2005-01-03 00:00:00.000	2005-01-03	2005/01/0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DimDate {
            get {
                return ResourceManager.GetString("DimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	Continent	Asia				1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///2	Continent	Europe				1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///3	Continent	North America				1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///269	Country/Region	Asia			Armenia	1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///270	Country/Region	Asia			Australia	1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///271	Country/Region	Asia			Bhutan	1	2012-08-01 00:00:00.000	2012-08-01 00:00:00.000
        ///272	Country/Region	Asia			China	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DimGeography {
            get {
                return ResourceManager.GetString("DimGeography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	693	010112001	Seattle	Washington	United States	North America	4	35	2009-09-29 02:48:10.587		Current	1	2009-08-01 00:00:00.000	2009-08-01 00:00:00.000
        ///2	856	010112002	Kennewick	Washington	United States	North America	4	36	2009-09-29 02:48:10.587		Current	1	2009-08-01 00:00:00.000	2009-08-01 00:00:00.000
        ///3	424	010112003	Bellevue	Washington	United States	North America	4	37	2009-09-29 02:48:10.587		Current	1	2009-08-01 00:00:00.000	2009-08-01 00:00:00.000
        ///4	677	010112004	Redmond	Washington	United States	Nort [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DimSalesTerritory {
            get {
                return ResourceManager.GetString("DimSalesTerritory", resourceCulture);
            }
        }
    }
}
