//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenant.Mvc.Core.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatSectionLayout
    {
        public int SeatSectionLayoutId { get; set; }
        public Nullable<int> SeatSectionId { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<int> SkipCount { get; set; }
        public Nullable<int> StartNumber { get; set; }
        public Nullable<int> EndNumber { get; set; }
    }
}
