//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenant.Mvc.Core.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WingTipTicketsEntities : DbContext
    {
        public WingTipTicketsEntities()
            : base("name=WingTipTicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationDefault> ApplicationDefaults { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Concert> Concerts { get; set; }
        public virtual DbSet<CustomerCreditCard> CustomerCreditCards { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Organizer> Organizers { get; set; }
        public virtual DbSet<Performer> Performers { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TicketLevel> TicketLevels { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
        public virtual DbSet<WebSiteActionLog> WebSiteActionLogs { get; set; }
        public virtual DbSet<SeatSection> SeatSections { get; set; }
        public virtual DbSet<SeatSectionLayout> SeatSectionLayouts { get; set; }
    }
}
